name: Daily Company Reputation Tracker

on:
  schedule:
    - cron: '0 6 * * *'  # Run at 6:00 AM UTC every day
  workflow_dispatch:     # Manual trigger
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    
    env:
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run pipeline
        run: |
          python runner.py --all
      
      - name: Generate static data
        run: |
          python generate_static_data.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add static/data/* company_tracker.db logs/*.log
          git commit -m "Update data [skip ci]" || echo "No changes to commit"
          git push